BEGIN;

ALTER TABLE tenants ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS signup_token VARCHAR(128);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS token_expires_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS verification_tokens (
    token VARCHAR(128) PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    email VARCHAR(256),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    used BOOLEAN DEFAULT FALSE
);

COMMIT;
