"""DashBeam ↔ Crypto Wallets integration (especially Monero).

Securely share Monero view-only configs and subaddresses via DashBeam P2P.
HARD BLOCK: spend keys, seed phrases, and private keys are never transferable.
"""

from __future__ import annotations

from typing import Any

FORBIDDEN_KEYS = frozenset(
    {
        "spend_key",
        "spendkey",
        "secret_spend_key",
        "seed",
        "mnemonic",
        "seed_phrase",
        "private_key",
        "secret_key",
        "master_key",
        "wallet_password",
        "passphrase",
    }
)


class MoneroSharingValidator:
    """Validates Monero wallet data before P2P sharing.

    Ensures that ONLY view-only data is shared. Spend keys are
    blocked at the validation layer before any transfer begins.
    """

    def validate_share_data(self, data: dict[str, Any]) -> bool:
        """Scan data for forbidden spend-key fields. Raises on violation."""
        self._scan_dict(data, path="root")
        return True

    def _scan_dict(self, d: dict[str, Any], path: str) -> None:
        for key, value in d.items():
            full_path = f"{path}.{key}"
            if key.lower() in FORBIDDEN_KEYS:
                raise ValueError(
                    f"SPEND KEY BLOCKED at '{full_path}'. "
                    f"DashBeam never transfers spend keys."
                )
            if isinstance(value, dict):
                self._scan_dict(value, full_path)
            elif isinstance(value, list):
                for i, item in enumerate(value):
                    if isinstance(item, dict):
                        self._scan_dict(item, f"{full_path}[{i}]")

    def build_monero_share_payload(
        self,
        address: str,
        view_key: str,
        *,
        subaddresses: list[str] | None = None,
        label: str = "",
    ) -> dict[str, Any]:
        """Build a safe shareable Monero view-only payload.

        NEVER includes spend keys. Includes a clear warning.
        """
        # Validate inputs are plausible Monero data
        if len(address) < 90 or not address.startswith("4"):
            raise ValueError("Invalid Monero address format")
        if len(view_key) < 60:
            raise ValueError("Invalid Monero view key length")

        payload: dict[str, Any] = {
            "type": "monero_view_only_share",
            "address": address,
            "view_key": view_key,
            "subaddresses": subaddresses or [],
            "label": label,
            "warning": (
                "VIEW-ONLY CONFIGURATION — "
                "This data can only monitor incoming transactions. "
                "No spending capability. Generated by DashBeam Transfer."
            ),
        }
        return payload

    def is_monero_data(self, data: dict[str, Any]) -> bool:
        """Check if the shared data appears to be Monero wallet data."""
        return (
            data.get("type") == "monero_view_only_share"
            or "address" in data
            and "view_key" in data
        )
